version: "3.7"
services:
  app:
    image: knipknap/doorman-hub:latest
    ports:
      - 8888:80
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true   # otherwise RPI.GPIO refuses to run
    environment:
      - CRYPTO_SALT=abcdefg
      - GOOGLE_API_KEY=abcdefg
      - SUPPORT_EMAIL=none@gmail.com
      - SMTP_SERVER_AND_PORT=smtp.gmail.com:587
      - SMTP_USER=
      - SMTP_PASSWORD=
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DB=doorman
      - DB_USER=doorman
      - DB_PASSWORD=doorman-db-password
    #entrypoint: sh -c "while ! exec 6<>/dev/tcp/db/5432; do sleep 2; done; gunicorn -w 1 -b 0.0.0.0:80 doormanhub:app"

  db:
    image: postgres:14.1
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: doorman
      POSTGRES_USER: doorman
      POSTGRES_PASSWORD: doorman-db-password

volumes:
  db-data:
